version: '3'

services:

  postgres:
    image: postgres:latest
    container_name: codechella_db
    restart: always
    environment:
      - POSTGRES_DB=codechella_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"